"""Initial schema with 9 tables

Revision ID: 51def9469a47
Revises: 
Create Date: 2025-11-10 10:19:55.279467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51def9469a47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_gaps',
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('niche', sa.String(length=100), nullable=False),
    sa.Column('gap_type', sa.Enum('FORMAT_GAP', 'QUALITY_GAP', 'DEPTH_GAP', 'RECENCY_GAP', 'AUDIENCE_GAP', name='gaptype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommended_approach', sa.Text(), nullable=True),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('current_competition', sa.Integer(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('missing_formats', sa.JSON(), nullable=True),
    sa.Column('missing_angles', sa.JSON(), nullable=True),
    sa.Column('target_audience', sa.String(length=200), nullable=True),
    sa.Column('audience_size', sa.Integer(), nullable=True),
    sa.Column('related_topics', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('validated', sa.Integer(), nullable=True),
    sa.Column('exploited', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_gaps_gap_type'), 'content_gaps', ['gap_type'], unique=False)
    op.create_index(op.f('ix_content_gaps_id'), 'content_gaps', ['id'], unique=False)
    op.create_index(op.f('ix_content_gaps_niche'), 'content_gaps', ['niche'], unique=False)
    op.create_index(op.f('ix_content_gaps_topic'), 'content_gaps', ['topic'], unique=False)
    op.create_table('niche_configs',
    sa.Column('niche_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('seed_topics', sa.JSON(), nullable=True),
    sa.Column('google_trends_enabled', sa.Integer(), nullable=True),
    sa.Column('google_trends_weight', sa.Float(), nullable=True),
    sa.Column('reddit_enabled', sa.Integer(), nullable=True),
    sa.Column('reddit_weight', sa.Float(), nullable=True),
    sa.Column('reddit_subreddits', sa.JSON(), nullable=True),
    sa.Column('min_search_volume', sa.Integer(), nullable=True),
    sa.Column('max_competition', sa.Float(), nullable=True),
    sa.Column('min_opportunity_score', sa.Float(), nullable=True),
    sa.Column('preferred_formats', sa.JSON(), nullable=True),
    sa.Column('excluded_formats', sa.JSON(), nullable=True),
    sa.Column('target_regions', sa.JSON(), nullable=True),
    sa.Column('target_languages', sa.JSON(), nullable=True),
    sa.Column('custom_settings', sa.JSON(), nullable=True),
    sa.Column('config_file_path', sa.String(length=500), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_niche_configs_id'), 'niche_configs', ['id'], unique=False)
    op.create_index(op.f('ix_niche_configs_niche_name'), 'niche_configs', ['niche_name'], unique=True)
    op.create_table('processing_jobs',
    sa.Column('job_type', sa.Enum('HORIZON_SCAN', 'SERP_SCRAPE', 'METRIC_ANALYSIS', 'FORMAT_CLASSIFICATION', 'FULL_PIPELINE', name='jobtype'), nullable=False),
    sa.Column('job_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('niche', sa.String(length=100), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.Integer(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('processed_items', sa.Integer(), nullable=True),
    sa.Column('failed_items', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('output_file', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('scheduled_for', sa.Integer(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('worker_hostname', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_id'), 'processing_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_job_status'), 'processing_jobs', ['job_status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_job_type'), 'processing_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_processing_jobs_niche'), 'processing_jobs', ['niche'], unique=False)
    op.create_table('seed_topics',
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('source', sa.Enum('GOOGLE_TRENDS', 'REDDIT', 'MANUAL', name='sourcetype'), nullable=False),
    sa.Column('niche', sa.String(length=100), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('trend_status', sa.Enum('RISING', 'PEAK', 'DECLINING', 'STABLE', name='trendstatus'), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_metadata', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seed_topics_id'), 'seed_topics', ['id'], unique=False)
    op.create_index(op.f('ix_seed_topics_niche'), 'seed_topics', ['niche'], unique=False)
    op.create_index(op.f('ix_seed_topics_source'), 'seed_topics', ['source'], unique=False)
    op.create_index(op.f('ix_seed_topics_topic'), 'seed_topics', ['topic'], unique=False)
    op.create_table('search_queries',
    sa.Column('query_text', sa.String(length=500), nullable=False),
    sa.Column('seed_topic_id', sa.Integer(), nullable=True),
    sa.Column('niche', sa.String(length=100), nullable=True),
    sa.Column('max_results', sa.Integer(), nullable=True),
    sa.Column('region_code', sa.String(length=5), nullable=True),
    sa.Column('language_code', sa.String(length=5), nullable=True),
    sa.Column('total_results', sa.Integer(), nullable=True),
    sa.Column('videos_scraped', sa.Integer(), nullable=True),
    sa.Column('search_method', sa.String(length=50), nullable=True),
    sa.Column('execution_time_seconds', sa.Integer(), nullable=True),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seed_topic_id'], ['seed_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_id'), 'search_queries', ['id'], unique=False)
    op.create_index(op.f('ix_search_queries_niche'), 'search_queries', ['niche'], unique=False)
    op.create_index(op.f('ix_search_queries_query_text'), 'search_queries', ['query_text'], unique=False)
    op.create_index(op.f('ix_search_queries_seed_topic_id'), 'search_queries', ['seed_topic_id'], unique=False)
    op.create_table('videos',
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=True),
    sa.Column('channel_name', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('search_query_id', sa.Integer(), nullable=True),
    sa.Column('search_rank', sa.Integer(), nullable=True),
    sa.Column('metrics_analyzed', sa.Boolean(), nullable=True),
    sa.Column('format_classified', sa.Boolean(), nullable=True),
    sa.Column('transcript_downloaded', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_channel_id'), 'videos', ['channel_id'], unique=False)
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.create_index(op.f('ix_videos_search_query_id'), 'videos', ['search_query_id'], unique=False)
    op.create_index(op.f('ix_videos_video_id'), 'videos', ['video_id'], unique=True)
    op.create_table('opportunity_scores',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('search_volume_score', sa.Float(), nullable=True),
    sa.Column('competition_score', sa.Float(), nullable=True),
    sa.Column('velocity_score', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('recency_score', sa.Float(), nullable=True),
    sa.Column('competition_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='competitionlevel'), nullable=True),
    sa.Column('total_competing_videos', sa.Integer(), nullable=True),
    sa.Column('average_competitor_views', sa.Integer(), nullable=True),
    sa.Column('content_gap_identified', sa.Text(), nullable=True),
    sa.Column('recommended_angle', sa.Text(), nullable=True),
    sa.Column('weights', sa.Float(), nullable=True),
    sa.Column('trend_prediction', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_recommended', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_scores_competition_level'), 'opportunity_scores', ['competition_level'], unique=False)
    op.create_index(op.f('ix_opportunity_scores_id'), 'opportunity_scores', ['id'], unique=False)
    op.create_index(op.f('ix_opportunity_scores_overall_score'), 'opportunity_scores', ['overall_score'], unique=False)
    op.create_index(op.f('ix_opportunity_scores_video_id'), 'opportunity_scores', ['video_id'], unique=True)
    op.create_table('video_formats',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('predicted_format', sa.Enum('TUTORIAL', 'LISTICLE', 'NEWS', 'REVIEW', 'COMPARISON', 'VLOG', 'INTERVIEW', 'EXPLAINER', 'ENTERTAINMENT', 'OTHER', name='videoformattype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('alternative_formats', sa.JSON(), nullable=True),
    sa.Column('transcript_available', sa.Integer(), nullable=True),
    sa.Column('transcript_length', sa.Integer(), nullable=True),
    sa.Column('transcript_summary', sa.Text(), nullable=True),
    sa.Column('has_step_by_step', sa.Integer(), nullable=True),
    sa.Column('has_numbered_list', sa.Integer(), nullable=True),
    sa.Column('has_comparison', sa.Integer(), nullable=True),
    sa.Column('has_personal_story', sa.Integer(), nullable=True),
    sa.Column('key_phrases', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.Text(), nullable=True),
    sa.Column('pacing', sa.Text(), nullable=True),
    sa.Column('audio_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('speaking_rate', sa.Float(), nullable=True),
    sa.Column('silence_ratio', sa.Float(), nullable=True),
    sa.Column('structure_detected', sa.JSON(), nullable=True),
    sa.Column('hook_effectiveness', sa.Float(), nullable=True),
    sa.Column('transcription_model', sa.Text(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_formats_id'), 'video_formats', ['id'], unique=False)
    op.create_index(op.f('ix_video_formats_predicted_format'), 'video_formats', ['predicted_format'], unique=False)
    op.create_index(op.f('ix_video_formats_video_id'), 'video_formats', ['video_id'], unique=True)
    op.create_table('video_metrics',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('dislike_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('like_ratio', sa.Float(), nullable=True),
    sa.Column('comment_rate', sa.Float(), nullable=True),
    sa.Column('views_per_day', sa.Float(), nullable=True),
    sa.Column('recent_view_velocity', sa.Float(), nullable=True),
    sa.Column('keyword_search_volume', sa.Integer(), nullable=True),
    sa.Column('keyword_competition', sa.Float(), nullable=True),
    sa.Column('keyword_cpc', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_magnitude', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subscriber_view_ratio', sa.Float(), nullable=True),
    sa.Column('virality_score', sa.Float(), nullable=True),
    sa.Column('youtube_api_response', sa.JSON(), nullable=True),
    sa.Column('google_ads_response', sa.JSON(), nullable=True),
    sa.Column('analysis_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_metrics_id'), 'video_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_video_metrics_video_id'), 'video_metrics', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_metrics_video_id'), table_name='video_metrics')
    op.drop_index(op.f('ix_video_metrics_id'), table_name='video_metrics')
    op.drop_table('video_metrics')
    op.drop_index(op.f('ix_video_formats_video_id'), table_name='video_formats')
    op.drop_index(op.f('ix_video_formats_predicted_format'), table_name='video_formats')
    op.drop_index(op.f('ix_video_formats_id'), table_name='video_formats')
    op.drop_table('video_formats')
    op.drop_index(op.f('ix_opportunity_scores_video_id'), table_name='opportunity_scores')
    op.drop_index(op.f('ix_opportunity_scores_overall_score'), table_name='opportunity_scores')
    op.drop_index(op.f('ix_opportunity_scores_id'), table_name='opportunity_scores')
    op.drop_index(op.f('ix_opportunity_scores_competition_level'), table_name='opportunity_scores')
    op.drop_table('opportunity_scores')
    op.drop_index(op.f('ix_videos_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_search_query_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_channel_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_search_queries_seed_topic_id'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_query_text'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_niche'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_id'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_seed_topics_topic'), table_name='seed_topics')
    op.drop_index(op.f('ix_seed_topics_source'), table_name='seed_topics')
    op.drop_index(op.f('ix_seed_topics_niche'), table_name='seed_topics')
    op.drop_index(op.f('ix_seed_topics_id'), table_name='seed_topics')
    op.drop_table('seed_topics')
    op.drop_index(op.f('ix_processing_jobs_niche'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_job_type'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_job_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_niche_configs_niche_name'), table_name='niche_configs')
    op.drop_index(op.f('ix_niche_configs_id'), table_name='niche_configs')
    op.drop_table('niche_configs')
    op.drop_index(op.f('ix_content_gaps_topic'), table_name='content_gaps')
    op.drop_index(op.f('ix_content_gaps_niche'), table_name='content_gaps')
    op.drop_index(op.f('ix_content_gaps_id'), table_name='content_gaps')
    op.drop_index(op.f('ix_content_gaps_gap_type'), table_name='content_gaps')
    op.drop_table('content_gaps')
    # ### end Alembic commands ###
